version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
  myapp:
    image: demo:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - postgres


#para iniciar usar docker-compose up