#Define a imagem do postgres na versão 14
FROM postgres:14-alpine

#Expoe a porta 5432
EXPOSE 5432

#define o comando que sera executado quando iniciar o container
CMD ["postgres"]

#Comandos para iniciar:
# Criar imagem: docker build -t postgres:14-local .
# Após criar imagem, executar com: docker run -d -p 5432:5432 postgres:14-local
